apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-simple
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
