apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-simple
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/reikamoon/guestbook # Watch for new versions of this image
      semverConstraint: ^1.24.0
      tagSelectionStrategy: SemVer
